name: jasontest
favicon: null
layout_spectrum: 0.8144209624733776
typography_spectrum: 0.7415894637815654
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.06630132463760674
  lightness: 0.6964149016421288
  saturation: 0.5391112000215799
  rhythmicContrast: 0.3197108507156372
purpose: []
